列挙値の入力値バリデーションを追加する
nablarch/nablarch-core-validation-ee pull request #22
Opened 2023-05-08 12:21 UTC by chupaaaaaaan

https://milky.adc-tis.com/redmine/issues/52632
に対応しました。

2023-05-09 04:54 UTC, kumagoro1202 requested changes

2023-05-09 04:54 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> + * public enum SampleEnum implements EnValue{@code <String>} {
`implements EnValue`は`WithValue`の誤り？

2023-05-09 04:54 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +public @interface IncludedIn {
IncludeInだと意味が広すぎてEnumのバリデーションとはわからないと思います。Javadocを眺めた時にどんなバリデーションをするのか名前だけでわかるようにして欲しいです。EnumValueとかでいいんじゃないですか。

2023-05-09 04:54 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +            if (value == null || value instanceof String && StringUtil.isNullOrEmpty((String) value)) {
全体的に条件式が3個以上の王権式の論理和/論理積になっているものは、優先順位の高い論理積の結合部分を（）で囲んでほしいです。論理積の方が優先順位高いのは常識とは言えぱっと見た時の可読性の点で囲んである方が読みやすいです。

```java
value == null || value instanceof String && StringUtil.isNullOrEmpty((String) value)
```
より
```java
value == null || (value instanceof String && StringUtil.isNullOrEmpty((String) value))
```

```java
caseInsensitive && value.toString().equalsIgnoreCase(e.name()) || value.toString().equals(e.name())
```
より
```java
(caseInsensitive && value.toString().equalsIgnoreCase(e.name())) || value.toString().equals(e.name())
```
の方が読みやすいです。

2023-05-09 04:54 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> + *         この場合、{@link #caseInsensitive()}を指定しても効果は無い（{@link WithValue#getValue()}で自由に制御できるため）。
この場合、caseInsensitiveを指定しても効果は無いではなく、caseInsensitiveは無視され常に大文字小文字を区別するとかの方がいいと思います。あと(WithValueで自由に～)という部分は要らないと思います。何を言いたいのかがわかりにくいので。多分大文字小文字区別したくないならgetValueで大文字か小文字に統一して返すようにして入力値もそれにあわせて大文字か小文字に統一してくれ的なことを書きたいのかなと思いましたが、なくてもいい情報かなと思いました。

2023-05-09 04:54 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +                    }
ここを通るテストがありません。

2023-05-09 04:54 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +                        if (caseInsensitive && value.toString().equalsIgnoreCase(e.name()) || value.toString().equals(e.name())) {
instanceofでString型の判定したvalue対してtoStringするのは違和感があります。キャストするだけでいいのでは。

2023-05-09 04:54 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +                        enValue instanceof BigDecimal && value instanceof BigDecimal) {
BigDecimalだったら直接equals使えるのでここの分岐に入れているのかと思いますが、コメントで「String/Numberのみ許可する」と書いているので少し混乱しました。
BigDecimalだけ特別扱いせずに下のNumber型の分岐に入れてしまったほうが読みやすくなるかと思いました。

2023-05-09 04:54 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +                    if (enValue instanceof String && value instanceof String ||
enValueとvalueが違う型のパターンのテストが網羅されていません。
（enValueはStringだけどvalueがStringでないパターンなど）

2023-05-09 06:05 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> + * public enum SampleEnum implements EnValue{@code <String>} {
誤りです。`WithValue`に修正しました。

2023-05-09 06:07 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +public @interface IncludedIn {
`EnumElement`としました（ `EnumValue`と似ていますが、内部インタフェースの `WithValue` も考慮すると、Valueが2回重ならない方がいいかなと）。

2023-05-09 06:17 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> + *         この場合、{@link #caseInsensitive()}を指定しても効果は無い（{@link WithValue#getValue()}で自由に制御できるため）。
「無視される」のみの記載に修正しました。

> あと(WithValueで自由に～)という部分は要らないと思います。何を言いたいのかがわかりにくいので。多分大文字小文字区別したくないならgetValueで大文字か小文字に統一して返すようにして入力値もそれにあわせて大文字か小文字に統一してくれ的なことを書きたいのかなと思いましたが、なくてもいい情報かなと思いました。

ここでの意図は、「入力値との比較ロジックを`WithValue#getValue()`が受け持つことになるので、`EnumElement#caseInsensitive()`で比較ロジック(大文字小文字の区別有無)は制御できなくなる」というものでした。
そのため、「無視される」のみで意図は伝わると考えています。

2023-05-09 06:20 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +                        enValue instanceof BigDecimal && value instanceof BigDecimal) {
`BigDecimal(BigDecimal)`のシグネチャのコンストラクタがないので、そのまま`Number`型の分岐に入れることはできません。
少し重複しますが、可読性を考慮して上記if文（およびコメント）を分割しました（合わせてテストも追加）

2023-05-09 06:20 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +                        if (caseInsensitive && value.toString().equalsIgnoreCase(e.name()) || value.toString().equals(e.name())) {
キャストに修正しました。

2023-05-09 06:24 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +            if (value == null || value instanceof String && StringUtil.isNullOrEmpty((String) value)) {
修正しました。

2023-05-09 06:29 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +                    }
`public void 入力値がStringの場合に列挙型定数のNumber型フィールドと比較する場合は検証失敗する()`としてテスト追加しました。

2023-05-09 08:59 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/IncludedIn.java
> +                    if (enValue instanceof String && value instanceof String ||
分岐網羅が100%になっていることを確認しました。

2023-05-10 07:30 UTC, kumagoro1202 requested changes

2023-05-10 07:30 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/EnumElement.java
> + *         区別する場合は{@link #caseSensitive()}を{@code false}に設定する（デフォルト:{@code true}）。
true/false反対になってる。

2023-05-10 07:30 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/EnumElement.java
> +            }
`constraintAnnotation.value()`は一回変数に入れましょう。

2023-05-10 07:30 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/EnumElement.java
> +                    throw new IllegalArgumentException("The return type of EnumElement.WithValue#getValue() is only String or Number.");
○○ is only XX だとニュアンスに違和感があります。StringかNumberだけが許容されるというニュアンスがなく、事実として返ってくるのはStringかNumberだけですと宣言しているような文章に感じます。
`The return type of EnumElement.WithValue#getValue()  must be String or Number.`とかがいいんじゃないかと思います。

2023-05-10 07:41 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/EnumElement.java
> + *         区別する場合は{@link #caseSensitive()}を{@code false}に設定する（デフォルト:{@code true}）。
修正しました。

2023-05-10 07:41 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/EnumElement.java
> +            }
修正しました。

2023-05-10 07:42 UTC, chupaaaaaaan commented on src/main/java/nablarch/core/validation/ee/EnumElement.java
> +                    throw new IllegalArgumentException("The return type of EnumElement.WithValue#getValue() is only String or Number.");
確かに変ですね・・・気づきませんでした。「must be」に修正しました。

2023-05-10 07:50 UTC, kumagoro1202 approved these changes

2023-05-10 07:50 UTC, merged