日付の入力値バリデーションを作成しました
nablarch/nablarch-core-validation-ee pull request #23
Opened 2023-05-11 11:58 UTC by chupaaaaaaan

2023-05-11 12:10 UTC, kumagoro1202 requested changes

2023-05-11 12:10 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> + * 日付書式の設定方法は、優先度の高い順に以下の3つとなる（優先度の高い設定方法での値は、優先度の低い設定方法での値を上書きする）。
カッコ内は冗長なので要らないと思います。

2023-05-11 12:10 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> + * </ol>
- 日付書式はvalue属性に指定する。
- value属性が指定されていない場合は、デフォルトの書式でバリデーションする。
- デフォルトの書式はyyyyMMdd。デフォルト書式を変更する場合はnablarch.dateFormatValidator.defaultFormatという名前でプロパティファイルに設定する。

ぐらいの書き方がいいと思います。「アノテーションを付与する対象毎に設定する日付書式を変更したい場合は、この方法を使用する。」とか「後方互換のために設定であり、～」とかは情報としては利用者にあまり価値がないと思います。
「そのため、この日付書式がプロジェクト要件を満たすものであっても、上記2つの方法のいずれかで日付書式文字列を設定すること。」これもそう制限する必要性がわからないです。yyyyMMddでいいなら指定なしで使えばいいと思います。アーキタイプで最初から設定されるからわざわざ消すことはないでしょうというだけの話だと思います。

2023-05-11 12:11 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> + * 日付書式の設定方法は、優先度の高い順に以下の3つとなる（優先度の高い設定方法での値は、優先度の低い設定方法での値を上書きする）。
下の指摘とあわせてこの文章自体要らなくなると思います。

2023-05-11 12:20 UTC, kumagoro1202 requested changes

2023-05-11 12:20 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +        public static final String PROPS_DEFAULT_FORMAT = "nablarch.dateFormatValidator.defaultFormat";
KEYとかNAMEとかのサフィックスが付いてる方がしっくりきます。他のクラスではそうなってるはず。

2023-05-11 12:20 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +         */
Javadoc中途半端になってるので書くか消すかしてください。

2023-05-11 12:20 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +                throw new IllegalStateException("Invalid date format string. [" + formatString + "]");
メッセージにstringは要らないと思います。

2023-05-11 12:20 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +            // そのため、単に非nullチェックを実施すればよい。
これは実装時のメモ書き？コメントとして残すものではないと思います。実在しない日付がエラーになるのはgetParsedDateのJavadocを読めばわかるので。

2023-05-11 12:20 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> + *     <li>入力値が、{@link java.text.SimpleDateFormat}に準拠した日付書式に一致していること。</li>
準拠した日付書式がどこから現れたのかわからないので意味がわかりにくいです。
**指定した**日付書式に一致していることとするべきかと思います。

2023-05-11 12:27 UTC, kumagoro1202 requested changes

2023-05-11 12:27 UTC, kumagoro1202 commented on src/test/java/nablarch/core/validation/ee/BeanValidationTestCase.java
> +        SystemRepository.load(new DiContainer(new XmlComponentDefinitionLoader(componentFileUrl)));
1個だけのプロパティを読み込むためにわざわざこのメソッドとXML、propertiesファイル作らなくてもObjectLoaderの匿名クラス作った方が早いのでは？

2023-05-12 00:37 UTC, kumagoro1202 requested changes

2023-05-12 00:37 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> + *     <li>{@link java.text.SimpleDateFormat}の厳密な日時解析の結果、入力値が正当な日付と判定されること。</li>
「実在日付であること」くらいでいいと思います。

2023-05-12 00:37 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +        private String getDefaultFormat() {
Javadoc書くか消すかしてください。

2023-05-12 00:41 UTC, kumagoro1202 commented
日時、日付、時刻のそれぞれのフォーマット指定したテストがほしいです。

2023-05-12 01:41 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +        public static final String PROPS_DEFAULT_FORMAT = "nablarch.dateFormatValidator.defaultFormat";
検索してみると、プロパティ名の定数名パターンは、`SYSTEM_PROP_XXX`、`PROPS_XXX`、`XXX_PROP_NAME`の3つあるような感じでした。
リポジトリやセッション等のキー名には`_KEY`をよくつけられているようですが、プロパティ名には使っていないようでした。
`_NAME`については、`_PROP_NAME`のような使用例が1つありますが、`_NAME`単独だとクラス名等の名前を指定するプロパティである場合にややこしそうには思いました。
`PROPS_XXX`はログ系でだけ使われているようで、数自体は一番多いのですが、複数形にする理由はなさそうなので、`SYSTEM_PROP_XXX`系に合わせて`PROP_XXX`に変更しようと思います。

https://github.com/search?q=org%3Anablarch+language%3AJava+_KEY&type=code
https://github.com/search?q=org%3Anablarch+language%3AJava+_NAME&type=code
https://github.com/search?q=org%3Anablarch+language%3AJava+PROP_&type=code&l=Java
https://github.com/search?q=org%3Anablarch+language%3AJava+PROPS_&type=code

2023-05-12 02:05 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +         */
javadoc追加しました。

e6ccdd17e679303a1ae1bec8f9a10ee2b77fa5e2

2023-05-12 02:06 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +        private String getDefaultFormat() {
javadoc追加しました。

e6ccdd17e679303a1ae1bec8f9a10ee2b77fa5e2

2023-05-12 02:08 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +                throw new IllegalStateException("Invalid date format string. [" + formatString + "]");
削除しました。

56aaa9310a828a5039cf5f734757cd784c8d100d

2023-05-12 02:08 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +            // そのため、単に非nullチェックを実施すればよい。
削除しました。

2a667ea283b15bfa5df813ab7ad2fd709d965ad1

2023-05-12 02:09 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> + * </ol>
Javadoc見直しました。

9b32297bad631c37a78c73cdae2d2ab30517bc26

2023-05-12 02:09 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> + * 日付書式の設定方法は、優先度の高い順に以下の3つとなる（優先度の高い設定方法での値は、優先度の低い設定方法での値を上書きする）。
下で合わせて対応しました。

2023-05-12 02:09 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> + *     <li>入力値が、{@link java.text.SimpleDateFormat}に準拠した日付書式に一致していること。</li>
上で合わせて対応しました。

2023-05-12 02:16 UTC, hiji commented on src/test/java/nablarch/core/validation/ee/BeanValidationTestCase.java
> +        SystemRepository.load(new DiContainer(new XmlComponentDefinitionLoader(componentFileUrl)));
以下の理由で現在の実装になっています。
- Java8じゃないのでラムダで書けなくて匿名クラスではすっきり書けない
- 他のValidatorのテストに合わせて`BeanValidationTestCase`を継承しているので、それなら親クラスの機能を使う方が自然で、統一感もあると思えた
- プロパティベースで定義した方が実態に即している

それほど手間になるわけではないと思うので、そこまでの問題でなければそのままとさせてください。

2023-05-12 02:21 UTC, hiji commented
> 日時、日付、時刻のそれぞれのフォーマット指定したテストがほしいです。

追加しました。

b4a053936f33d5b4e335a628c652830c227fe2aa

2023-05-12 02:30 UTC, kumagoro1202 commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +        public static final String PROPS_DEFAULT_FORMAT = "nablarch.dateFormatValidator.defaultFormat";
気にしているのは、定数`DEFAULT_FORMAT`にはその名の通りフォーマットが入っていて、同様の名前である`PROP_DEFAULT_FORMAT`にはプロパティとして取得する名前が入っていることに統一感がないなということです。
`PROP_`というプリフィクスではプロパティから取ってきたというイメージしかなく、`PROP_DEFAULT_FORMAT`にはフォーマットが入っていそうに思えます。
`PROP_DEFAULT_FORMAT_NAME`ならプロパティから取得するデフォルトフォーマットの名前(プロパティ名ですが実態としてシステムリポジトリから取得するキーなので`_KEY`もありだと思います。)になって区別がつくかなと。
`PROP_DEFAULT_FORMAT`単体というより、同じクラスにある`DEFAULT_FORMAT`との対比で違和感があります。

2023-05-12 02:35 UTC, kumagoro1202 commented on src/test/java/nablarch/core/validation/ee/BeanValidationTestCase.java
> +        SystemRepository.load(new DiContainer(new XmlComponentDefinitionLoader(componentFileUrl)));
同じく`BeanValidationTestCase`を継承してる`SystemCharValidatorTest`では`ObjetLoader`使用しています。
```
    @Test
    public void testSurrogateArrow() {
        //サロゲートペアを許容する設定を追加でloadする
        SystemRepository.load(new ObjectLoader() {
            public Map<String, Object> load() {
                SystemCharConfig config = new SystemCharConfig();
                config.setAllowSurrogatePair(true);
                return Collections.<String, Object> singletonMap("ee.SystemCharConfig", config);
            }
        });

        Set<?> violations = validator.validateValue(SurrogatePair.class, "test", "\uD867\uDE3D");
        assertThat(violations, empty());
    }
```

今回のだと
```
    @Test
    public void システムリポジトリに設定しているデフォルト書式で検証できる() {
        SystemRepository.load(new ObjectLoader() {
            public Map<String, Object> load() {
                return Collections.<String, Object> singletonMap("nablarch.dateFormatValidator.defaultFormat", "yyyy/MM/dd");
            }
        });
        TestBean bean = new TestBean();
        bean.defaultFormatInput = "2023/05/11";

        Set<ConstraintViolation<TestBean>> violations = validator.validate(bean);

        Assert.assertTrue(violations.isEmpty());

    }
```
とするだけで良いのでそっちの方がテストの見通し良くないですかね？
今の形だとXML見に行ってpropertiesファイル見に行ってと、どういうテストしてるのか見るのが割りと億劫に感じました。

2023-05-12 04:01 UTC, hiji commented on src/test/java/nablarch/core/validation/ee/BeanValidationTestCase.java
> +        SystemRepository.load(new DiContainer(new XmlComponentDefinitionLoader(componentFileUrl)));
（口頭で話しましたがこちらにも）
見通しというより、親クラスを他テストと同じく`BeanValidationTestCase`にしていますが、`BeanValidationTestCase`でSystemRopositoryの後処理や読込を実装しているため、SystemRepositoryの制御責務は親クラスにあるように見えます。そのため、それを無視して個別テストクラス内で上書きだけするのは、見通しとは別でクラス設計的な理由で違和感ありました。
（`SystemCharValidatorTest`では書かれているような`ObjetLoader`を生成して設定していますが、`prepareSystemRepository`を読んだ上でそれを個別テストで`ObjectLoader`を使って上書きし、後処理は親クラスに任せているので、`SystemCharValidatorTest`の実装自体が微妙だと思っています）

`ObjectLoader`を使って個別でSystemRepositoryを構築するのであれば、SystemRepositoryの後処理含めて個別テストクラス内で完結するのがよいと思うため、親クラスを外してSystemRepositoryの制御責務を個別テストに移すのがよいとは思います。

---
（親クラスを除去すると口頭で話しましたが考えを変更します）

上記の理由で本来は親クラスを外すか親クラスに任せるかどちらかだとは思うのですが、以下の理由で親クラスはそのままで`ObjectLoader`で設定するようにしました。

- いい実装とはいえないと思うが`SystemCharValidatorTest`で既に実装されてしまっている
- `DateFormatValidatorTest`だけ親クラスが無いのはそれはそれで浮いてしまって、メンテナンス時に疑問に思いそう

2023-05-12 04:25 UTC, hiji commented on src/main/java/nablarch/core/validation/ee/DateFormat.java
> +        public static final String PROPS_DEFAULT_FORMAT = "nablarch.dateFormatValidator.defaultFormat";
単体の話ではなく、クラス内の他定数との対比的にという話でしたら、仰る通り変えた方がよさそうに思いました。

`_KEY`をつけるのが分かりやすそうに思ったので修正しました。

0c1c195bea63de7fa05ad8e99ae882f11560a973

2023-05-12 04:57 UTC, kumagoro1202 approved these changes

2023-05-12 04:58 UTC, merged